### ISSUE TITLE
permission denied when snakemake is launched

### ISSUE THREAD

**Issue by MbDiop** [tdayris-perso/rna-count-salmon#7]
The following command doesn't work ` snakemake --profile .igr/profile/slurm`

Here is the error returned : 
```
Building DAG of jobs...
Creating conda environment https:/raw.githubusercontent.com/tdayris/snakemake-wrappers/Unofficial/bio/multiqc/environment.yaml...
Traceback (most recent call last):
  File "/mnt/beegfs/userdata/m_diop/conda/envs/rna-count-salmon/lib/python3.8/site-packages/snakemake/__init__.py", line 626, in snakemake
    success = workflow.execute(
  File "/mnt/beegfs/userdata/m_diop/conda/envs/rna-count-salmon/lib/python3.8/site-packages/snakemake/workflow.py", line 836, in execute
    dag.create_conda_envs(
  File "/mnt/beegfs/userdata/m_diop/conda/envs/rna-count-salmon/lib/python3.8/site-packages/snakemake/dag.py", line 275, in create_conda_envs
    env.create(dryrun)
  File "/mnt/beegfs/userdata/m_diop/conda/envs/rna-count-salmon/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 256, in create
    os.makedirs(env_path, exist_ok=True)
  File "/mnt/beegfs/userdata/m_diop/conda/envs/rna-count-salmon/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/beegfs/pipelines/rna-count-salmon/conda/42fd2856'

**Comment by tdayris-perso** [comment]
L'erreur vient du fait que `/mnt/beegfs/pipelines/rna-count-salmon/conda/` ne soit pas ouvert en écriture. Raison pour laquelle les pipelines n'y sont pas déposés.
